Everydayer/apps/planner/urls.py
from django.urls import path
from . import views

app_name = 'planner'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('create', views.create, name='create'),
    path('checkbox/<int:task_id>', views.checkbox, name='checkbox'),
    path('delete/<int:task_id>', views.delete, name='delete')
]

Everydayer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('planner/', include('planner.urls')),
    path('admin/', admin.site.urls),
]

Everydayer/apps/planner/models.py
from django.db import models


class Task(models.Model):
    task_title = models.CharField('название задания', max_length=128)
    task_description = models.TextField('описание задания')
    task_date = models.DateTimeField('дата и время задачи', blank=True, null=True)
    task_is_done = models.BooleanField('статус выполнения')

Everydayer/apps/planner/forms.py
from django import forms
from .models import Task


class DateInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class EditForm(forms.ModelForm):
    class Meta:
        model = Task
        widgets = {'my_datetime_field': DateInput()}
        fields = ('task_title', 'task_description', 'task_date')

Everydayer/apps/planner/views.py
import datetime

from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from Everydayer.apps.planner.models import Task
from django.urls import reverse
from datetime import timedelta

month_list = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь',
              'Декабрь']


def index(request):
    today = datetime.date.today()
    week = [today, today + timedelta(1), today + timedelta(2), today + timedelta(3), today + timedelta(4),
            today + timedelta(5), today + timedelta(6), today + timedelta(7)]
    latest_tasks = Task.objects.all()
    if week[0].day < week[7].day:
        month = month_list[today.month - 1]
    else:
        month = str(month_list[today.month - 1]) + " - " + str(month_list[today.month])

    return render(request, 'planner/list.html', {'latest_tasks': latest_tasks, 'week': week, 'month': month})


def detail(request, task_id):
    try:
        task = Task.objects.get(id=task_id)
    except:
        raise Http404("Таск не найден")

    return render(request, 'planner/edit.html', {'task': task})


def create(request):
    if request.POST:
        try:
            task = Task()
        except:
            raise Http404("Таск не удалось создать")

        task.task_title = request.POST['title']
        task.task_description = request.POST['description']
        task.task_date = request.POST['date'] + "+00:00"
        task.task_is_done = False
        task.save()

        return HttpResponseRedirect(reverse('planner:index'))
    # form = EditForm(request.POST or None)
    # if form.is_valid():
    #     form.save()

    return render(request, 'planner/create.html', {})


def delete(request, task_id):
    try:
        task = Task.objects.get(id=task_id)
    except:
        raise Http404("Таск не найден")

    task.delete()
    return HttpResponse("OK")


def edit(request, task_id):
    try:
        task = Task.objects.get(id=task_id)
    except:
        raise Http404("Таск не найден")

    task.task_title = request.POST['title']
    task.task_description = request.POST['description']
    task.task_date = request.POST['date'] + "+00:00"
    task.save()

    return HttpResponseRedirect(reverse('planner:index'))


def checkbox(request, task_id):
    try:
        task = Task.objects.get(id=task_id)
    except:
        raise Http404("Неправильно изменил checkbox")

    task.task_is_done = not task.task_is_done
    task.save()

    return HttpResponse("ok")

Everydayer/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link href="{% static '/all.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/c2e29beef4.js" crossorigin="anonymous"></script>
    <style>
        body {
            font-family: 'Open Sans';
        }
    </style>
</head>
<body>
    {% block content %}
    
    {% endblock %}

</body>
</html>

Everydayer/templates/planner/create.html
{% extends 'base.html' %}

{% block title %}Создание таска{% endblock %}

{% block content %}
<style>
.title {
    font-size: 2em;
    padding: 20px 5px;
}
article {
    margin-left: 5px;
}
input, textarea, button {
    margin: 5px;
    width: 200px;
}
input, textarea {
    padding: 5px;
    border: 1px solid gray;
    border-radius: 3px;
}
button {
    width: 212px;
    padding: 10px 20px;
    color: black;
    background-color: #fff;
    border: 1px solid #000;
    border-radius: 3px;
    transition: .2s;
}
button:hover {
    border: 1px solid #cb0f00;
    background-color: #cb0f00;
    color: white;
    cursor: pointer;
}
</style>
<div class="title">Создание таска</div>
<form method="POST">
    {% csrf_token %}
    <article>Название:</article>
    <input type="text" placeholder="Название" name="title"><br>
    <article>Описание:</article>
    <textarea cols="30" rows="10" name="description" placeholder="Описание"></textarea><br>
    <article>Дата события</article>
    <input type="datetime-local" name="date"><br>
    <button type="submit">Создать таск</button>
</form>
{% endblock %}

Everydayer/templates/planner/edit.html
{% extends 'base.html' %}

{% block title %}{{ task.task_title }}{% endblock %}

{% block content %}

<style>
.title {
    font-size: 2em;
    padding: 20px 5px;
}
article {
    margin-left: 5px;
}
input, textarea, button {
    margin: 5px;
    width: 200px;
}
input, textarea {
    padding: 5px;
    border: 1px solid gray;
    border-radius: 3px;
}
button {
    width: 212px;
    padding: 10px 20px;
    color: black;
    background-color: #fff;
    border: 1px solid #000;
    border-radius: 3px;
    transition: .2s;
}
button:hover {
    border: 1px solid #cb0f00;
    background-color: #cb0f00;
    color: white;
    cursor: pointer;
}
</style>
<div class="title">Изменение таска</div>
<form action="{% url 'planner:edit' task.id %}" method="POST">
    {% csrf_token %}
    <article>Название:</article>
    <input type="text" placeholder="Название" name="title" value="{{ task.task_title }}"><br>
    <article>Описание:</article>
    <textarea rows="10" name="description" placeholder="Описание">{{ task.task_description }}</textarea><br>
    <article>Дата события</article>
    <input type="datetime-local" name="date" value="{{ task.task_date|date:"Y-m-d\TH:i" }}"><br>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

Everydayer/templates/planner/list.html
{% extends 'base.html' %}

{% block title %}Последние таски{% endblock %}

{% block content %}
    <style>
    .week {
        display: flex;
        justify-content: space-between;
    }
    .day {
        min-width: 100px;
    }
    .btn {
        border: 0;
        background-color: transparent;
        transition: .2s;
    }
    .btn:hover {
        opacity: .7;
        cursor: pointer;
    }
    .month {
        font-size: 2em;
        display: inline;
    }
    .addTask {
        border: 2px solid black;
        border-radius: 100%;
        height: 30px;
        width: 30px;
        display: inline;
        line-height: 25px;
        transform: translateY(-4px);
        transition: .2s;
    }
    .addTask:hover {
        background-color: #000;
        color: white;
    }
    </style>
    <div class="month">{{ month }}</div>
    <button class="btn addTask" onclick="window.location.href='{% url 'planner:create' %}'"><i class="fas fa-plus"></i></button>
    {% if latest_tasks %}


        <div class="week">
            {% for day in week %}
                <div class="day">
                    <h2>{{ day.day }}</h2>
                    {% for i in latest_tasks %}
                        {% if i.task_date.year == day.year %}
                            {% if i.task_date.month == day.month %}
                                {% if i.task_date.day == day.day %}
                                    <p id="task{{ i.id }}">
                                        {% if i.task_is_done %}
                                            <input type="checkbox" id="chBoxId{{ i.id }}" onclick="changeCheckbox({{ i.id }});" checked/>
                                        {% else %}
                                            <input type="checkbox" id="chBoxId{{ i.id }}" onclick="changeCheckbox({{ i.id }});" />
                                        {% endif %}
                                        {{ i.task_title }}
                                        <button class="btn" onclick="window.location.href='{% url 'planner:detail' i.id %}'"><i class="fas fa-edit"></i></button>
                                        <button class="btn" onclick="deleteTask({{ i.id }})"><i class="fas fa-trash"></i></button>
                                    </p>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>

    {% else %}
        Таски не найдены
    {% endif %}

    <script>
    function changeCheckbox(id) {
        var req = getXmlHttp();
        var box = document.getElementById('chBoxId'+id);

        req.onreadystatechange = function() {
            if (req.readyState == 4) {
                if(req.status == 200) {
                    box.removeAttribute('disabled');
                    // alert("Ответ сервера: "+req.responseText);
                } else {
                    if (box.getAttribute('checked') == null){
                        box.setAttribute('checked', '');
                    } else {
                        box.removeAttribute('checked');
                    }
                }
            }
        };

        req.open('GET', 'checkbox/'+id, true);
        req.send(null);  // отослать запрос
        box.setAttribute('disabled', '');
    }

    function getXmlHttp(){
      var xmlhttp;
      try {
        xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
      } catch (e) {
        try {
          xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        } catch (E) {
          xmlhttp = false;
        }
      }
      if (!xmlhttp && typeof XMLHttpRequest!='undefined') {
        xmlhttp = new XMLHttpRequest();
      }
      return xmlhttp;
    }

    function deleteTask(id) {
        var req = getXmlHttp();
        var task = document.getElementById('task'+id);

        req.onreadystatechange = function() {
            if (req.readyState == 4) {
                if(req.status == 200) {
                    task.remove();
                } else {
                    task.removeAttribute('style');
                }
            }
        };

        req.open('GET', 'delete/'+id, true);
        req.send(null);  // отослать запрос
        task.setAttribute('style', 'opacity:0.5');
    }
    </script>
{% endblock %}